# Generated by Django 3.2.7 on 2021-10-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('players', models.ManyToManyField(to='main_app.Player')),
            ],
        ),
    ]
