# Generated by Django 3.2.7 on 2021-10-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_artist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
